version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  web:
    build: .
    container_name: web
    command: sh -c "python3 -m alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on: 
      - db

volumes:
  postgres_data:
